name: farmersguide
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.1
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add your assets for the splash screen
  assets:
    - assets/images/robotlogo.png.png # Path to your robot logo

# flutter_native_splash configuration
flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/images/robotlogo.png.png # Path to your robot logo
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  # title:
  #   text: "Farmers Guide" 
  #   color: "#000000" # Text color
  #   font_size: 40
  #   font_family: "Roboto" # Optional: Custom font family
